// Mock data for missing persons
export const MISSING_PERSONS = [
  {
    id: "1",
    name: "John Smith",
    age: 32,
    lastSeen: "2023-06-15",
    location: "Central Park, New York",
    coordinates: { lat: 40.7829, lng: -73.9654 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 5,
    status: "active",
    description:
      "John was last seen wearing a blue jacket and jeans. He is approximately 6'0\" tall with brown hair and blue eyes.",
    contact: "+1 (555) 123-4567",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    age: 17,
    lastSeen: "2023-06-18",
    location: "Downtown Seattle, WA",
    coordinates: { lat: 47.6062, lng: -122.3321 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 2,
    status: "active",
    description:
      "Sarah has blonde hair, brown eyes, and is approximately 5'4\" tall. She was last seen wearing a red hoodie and black pants.",
    contact: "+1 (555) 234-5678",
  },
  {
    id: "3",
    name: "Michael Chen",
    age: 24,
    lastSeen: "2023-06-10",
    location: "University District, Boston",
    coordinates: { lat: 42.3509, lng: -71.1084 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 10,
    status: "active",
    description:
      "Michael is 5'8\" with black hair and brown eyes. He was last seen wearing a grey t-shirt and blue jeans.",
    contact: "+1 (555) 345-6789",
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    age: 29,
    lastSeen: "2023-06-17",
    location: "Mission District, San Francisco",
    coordinates: { lat: 37.7599, lng: -122.4148 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 3,
    status: "active",
    description:
      "Emily has long brown hair and green eyes. She is approximately 5'6\" tall and was last seen wearing a black dress.",
    contact: "+1 (555) 456-7890",
  },
  {
    id: "5",
    name: "David Wilson",
    age: 42,
    lastSeen: "2023-06-12",
    location: "Shibuya, Tokyo, Japan",
    coordinates: { lat: 35.6602, lng: 139.6993 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 8,
    status: "active",
    description:
      "David has short brown hair and brown eyes. He is 5'11\" and was last seen wearing a business suit.",
    contact: "+81 90-1234-5678",
  },
  {
    id: "6",
    name: "Aisha Khan",
    age: 19,
    lastSeen: "2023-06-14",
    location: "Camden Town, London, UK",
    coordinates: { lat: 51.539, lng: -0.1426 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 6,
    status: "active",
    description:
      "Aisha has black hair and brown eyes. She is 5'5\" tall and was last seen wearing a blue denim jacket and black leggings.",
    contact: "+44 7700 900123",
  },
  {
    id: "7",
    name: "Carlos Mendez",
    age: 31,
    lastSeen: "2023-06-16",
    location: "Condesa, Mexico City, Mexico",
    coordinates: { lat: 19.4124, lng: -99.172 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 4,
    status: "active",
    description:
      "Carlos has black hair and brown eyes. He is 5'10\" tall and was last seen wearing khaki pants and a white shirt.",
    contact: "+52 55 1234 5678",
  },
  {
    id: "8",
    name: "Sophie Martin",
    age: 22,
    lastSeen: "2023-06-11",
    location: "Marais, Paris, France",
    coordinates: { lat: 48.8606, lng: 2.3522 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 9,
    status: "active",
    description:
      "Sophie has shoulder-length blonde hair and blue eyes. She is 5'7\" tall and was last seen wearing a black coat.",
    contact: "+33 6 12 34 56 78",
  },
  {
    id: "9",
    name: "Raj Patel",
    age: 27,
    lastSeen: "2023-06-13",
    location: "Colaba, Mumbai, India",
    coordinates: { lat: 18.9217, lng: 72.833 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 7,
    status: "active",
    description:
      "Raj has black hair and brown eyes. He is 5'9\" tall and was last seen wearing jeans and a striped t-shirt.",
    contact: "+91 98765 43210",
  },
  {
    id: "10",
    name: "Liu Wei",
    age: 35,
    lastSeen: "2023-06-09",
    location: "Sanlitun, Beijing, China",
    coordinates: { lat: 39.9403, lng: 116.4534 },
    imageUrl: "/placeholder.svg?height=300&width=300",
    daysAgo: 11,
    status: "active",
    description:
      "Liu has short black hair and brown eyes. He is 5'10\" tall and was last seen wearing a dark blue jacket.",
    contact: "+86 138 1234 5678",
  },
];

// Global regions for location filtering
export const GLOBAL_REGIONS = [
  { id: "north-america", name: "North America" },
  { id: "south-america", name: "South America" },
  { id: "europe", name: "Europe" },
  { id: "asia", name: "Asia" },
  { id: "africa", name: "Africa" },
  { id: "oceania", name: "Oceania" },
];

// Countries for location filtering
export const COUNTRIES = [
  { id: "us", name: "United States", region: "north-america" },
  { id: "ca", name: "Canada", region: "north-america" },
  { id: "mx", name: "Mexico", region: "north-america" },
  { id: "br", name: "Brazil", region: "south-america" },
  { id: "ar", name: "Argentina", region: "south-america" },
  { id: "gb", name: "United Kingdom", region: "europe" },
  { id: "fr", name: "France", region: "europe" },
  { id: "de", name: "Germany", region: "europe" },
  { id: "es", name: "Spain", region: "europe" },
  { id: "it", name: "Italy", region: "europe" },
  { id: "jp", name: "Japan", region: "asia" },
  { id: "cn", name: "China", region: "asia" },
  { id: "in", name: "India", region: "asia" },
  { id: "sg", name: "Singapore", region: "asia" },
  { id: "au", name: "Australia", region: "oceania" },
  { id: "nz", name: "New Zealand", region: "oceania" },
  { id: "za", name: "South Africa", region: "africa" },
  { id: "ng", name: "Nigeria", region: "africa" },
  { id: "eg", name: "Egypt", region: "africa" },
];

// Major cities for location filtering
export const MAJOR_CITIES = [
  {
    id: "nyc",
    name: "New York",
    country: "us",
    coordinates: { lat: 40.7128, lng: -74.006 },
  },
  {
    id: "lax",
    name: "Los Angeles",
    country: "us",
    coordinates: { lat: 34.0522, lng: -118.2437 },
  },
  {
    id: "chi",
    name: "Chicago",
    country: "us",
    coordinates: { lat: 41.8781, lng: -87.6298 },
  },
  {
    id: "tor",
    name: "Toronto",
    country: "ca",
    coordinates: { lat: 43.6532, lng: -79.3832 },
  },
  {
    id: "mex",
    name: "Mexico City",
    country: "mx",
    coordinates: { lat: 19.4326, lng: -99.1332 },
  },
  {
    id: "lon",
    name: "London",
    country: "gb",
    coordinates: { lat: 51.5074, lng: -0.1278 },
  },
  {
    id: "par",
    name: "Paris",
    country: "fr",
    coordinates: { lat: 48.8566, lng: 2.3522 },
  },
  {
    id: "ber",
    name: "Berlin",
    country: "de",
    coordinates: { lat: 52.52, lng: 13.405 },
  },
  {
    id: "mad",
    name: "Madrid",
    country: "es",
    coordinates: { lat: 40.4168, lng: -3.7038 },
  },
  {
    id: "rom",
    name: "Rome",
    country: "it",
    coordinates: { lat: 41.9028, lng: 12.4964 },
  },
  {
    id: "tok",
    name: "Tokyo",
    country: "jp",
    coordinates: { lat: 35.6762, lng: 139.6503 },
  },
  {
    id: "bei",
    name: "Beijing",
    country: "cn",
    coordinates: { lat: 39.9042, lng: 116.4074 },
  },
  {
    id: "mum",
    name: "Mumbai",
    country: "in",
    coordinates: { lat: 19.076, lng: 72.8777 },
  },
  {
    id: "syd",
    name: "Sydney",
    country: "au",
    coordinates: { lat: -33.8688, lng: 151.2093 },
  },
  {
    id: "cpt",
    name: "Cape Town",
    country: "za",
    coordinates: { lat: -33.9249, lng: 18.4241 },
  },
];
